services:
  desafiogestionna:
    depends_on:
      - db
    image: desafiogestionna
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      AzureServiceBus__QueueName: ${ServiceBus_Queue}
      ConnectionStrings__DefaultConnection: "Host=db; Port=5432; Username=local; Password=local; Database=gestionnna"
      AzureServiceBus__ConnectionString: ${ServiceBus_Connection}
    ports:
      - "4002:80"
    networks:
      - api-net
      - db-net
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: gestionnna
    volumes:
      # Mount the local directory to the container's init directory
      - ./init-scripts:/docker-entrypoint-initdb.d
      # Persist the actual database data
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-net

volumes:
  postgres_data:
networks:
  api-net:
  db-net: